# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      - master
      - alpha

jobs:
  test:
    uses: tksst/github-actions-workflows/.github/workflows/nodejs-pnpm.yml@60c5a837e7d460d37847306dd77c8df8ab7d06c6
    with:
      os: '["ubuntu-latest"]'
      build: false
      test: false
